services:
  - type: web
    name: pro-utaggerbot
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python "pro_utaggerbot (2).py"
    healthCheckPath: /
    envVars:
      - key: API_ID
        value: "38640395"
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: CUSTOM_EMOJI_PACK
        sync: false
      - key: DB_FILE
        value: /tmp/database22.db
      - key: CLONE_TOKEN_ENCRYPTION_KEY
        sync: false